const listings = [
   {
      title: 'new life cancer support group',
      displayTitle: 'New Life Cancer Support Group',
      learningOutcomes: 'This is the first website I made for a real client. I set up the workflow for the client to manage everything in the background. This is also the first time using Tailwind CSS.',
      builtWith: 'Desgned in Figma. Built with HTML, CSS, JavaScript, and Tailwind',
      liveLink: 'https://nlcsupportgroup.com/index.html',
      gitLink: 'https://github.com/Joshrobertson023/newlifecancer',
      imageSrc: './images/newlifecancer.jpg',
      inverse: true,
      category: 'websites',
   },
   {
      title: 'calculator',
      displayTitle: 'Calculator',
      learningOutcomes: 'This introduced me to manipulating the HTML in JavaScript and how to use arrays and strings as they were what made up the memory of this calculator.',
      builtWith: 'Built with HTML, CSS, and JavaScript',
      liveLink: 'https://joshrobertson023.github.io/calculator/',
      gitLink: 'https://github.com/Joshrobertson023/calculator',
      imageSrc: './images/Calculator.jpg',
      inverse: false,
      category: 'web-apps',
   },
   {
      title: 'searching algorithms',
      displayTitle: 'Searching Algorithms',
      learningOutcomes: 'This program taught me searching algorithms using whole numbers.',
      builtWith: 'Built with C',
      liveLink: '',
      gitLink: 'https://github.com/Joshrobertson023/Data-Structures-Algorithms/blob/main/program7.c',
      imageSrc: './images/searching-algorithms.jpg',
      inverse: true,
      category: 'c',
   },
   {
      title: 'tic tac toe',
      displayTitle: 'Tic-Tac-Toe',
      learningOutcomes: 'This project introduced me to various OOP concepts and working with JavaScript objects.',
      builtWith: 'Built with HTML, CSS, and JavaScript',
      liveLink: 'https://joshrobertson023.github.io/tic-tac-toe/',
      gitLink: 'https://github.com/Joshrobertson023/tic-tac-toe',
      imageSrc: './images/tictactoe.jpg',
      inverse: false,
      category: 'web-apps',
   },
   {
      title: 'etch a sketch',
      displayTitle: 'Etch-a-Sketch',
      learningOutcomes: 'This introduced me to working with basic logic and syntax in JavaScript. It also introduced me to manipulating a UI with code and working with the DOM.',
      builtWith: 'Built with HTML, CSS, and JavaScript',
      liveLink: 'https://joshrobertson023.github.io/etch-a-sketch/',
      gitLink: 'https://github.com/Joshrobertson023/etch-a-sketch',
      imageSrc: './images/etchasketch.jpg',
      inverse: true,
      category: 'web-apps',
   }
]

export {listings};