const listings = [
   {
      title: 'manage company employee bonuses',
      displayTitle: 'Manage Company Employee Bonuses',
      learningOutcomes: 'This program tested my skills with C++ as the first real-use program I wrote in the language. It implemented things I learned last semester and this semester.',
      builtWith: 'Built with C++.',
      liveLink: '',
      gitLink: 'https://github.com/Joshrobertson023/cs-246/blob/main/program6.cpp',
      imageSrc: './images/program6.png',
      inverse: false,
      category: 'cpp',
   },
   {
      title: 'square to circle area ratio',
      displayTitle: 'Square-to-circle Area Ratio',
      learningOutcomes: '...',
      builtWith: 'Built with C++.',
      liveLink: '',
      gitLink: 'https://github.com/Joshrobertson023/cs-246/blob/main/program5.cpp',
      imageSrc: './images/Square-to-circle.png',
      inverse: false,
      category: 'cpp',
   },
   {
      title: 'manage geometric shapes',
      displayTitle: 'Manage Geometric Shapes',
      learningOutcomes: 'This program brought all my C++ knowledge to use in one program. Classes, virtual functions, dynamic memory, and more.',
      builtWith: 'Built with C++.',
      liveLink: '',
      gitLink: 'https://www.dropbox.com/scl/fi/kq46gyl14mk03mupukz22/program4.cpp?rlkey=903flcmibzb9164tbc8rrndoi&dl=0',
      imageSrc: './images/program4.jpg',
      inverse: false,
      category: 'cpp',
   },
   {
      title: 'managing student records',
      displayTitle: 'Managing Student Records',
      learningOutcomes: 'This was the final project in my Data Structures and Algorithms class. The student records were implemented using a linear linked list. This project taught me how to create a basic linked list application.',
      builtWith: 'Built with C.',
      liveLink: '',
      gitLink: 'https://github.com/Joshrobertson023/Data-Structures-Algorithms/blob/main/program-code/program6.c',
      imageSrc: './images/searching-algorithms.jpg',
      inverse: false,
      category: 'c',
   },
   {
      title: 'new life cancer support group',
      displayTitle: 'New Life Cancer Support Group',
      learningOutcomes: 'This is the first website I made for a real client. I set up the workflow for the client to manage everything in the background. This is also the first time using Tailwind CSS.',
      builtWith: 'Desgned in Figma. Built with HTML, CSS, JavaScript, and Tailwind',
      liveLink: 'https://nlcsupportgroup.com/index.html',
      gitLink: 'https://github.com/Joshrobertson023/newlifecancer',
      imageSrc: './images/newlifecancer.jpg',
      inverse: false,
      category: 'webapps',
   },
   {
      title: 'calculator',
      displayTitle: 'Calculator',
      learningOutcomes: 'This introduced me to manipulating the HTML in JavaScript and how to use arrays and strings as they were what made up the memory of this calculator.',
      builtWith: 'Built with HTML, CSS, and JavaScript',
      liveLink: 'https://joshrobertson023.github.io/calculator/',
      gitLink: 'https://github.com/Joshrobertson023/calculator',
      imageSrc: './images/Calculator.jpg',
      inverse: false,
      category: 'webapps',
   },
   {
      title: 'searching algorithms',
      displayTitle: 'Searching Algorithms',
      learningOutcomes: 'This program taught me searching algorithms using whole numbers.',
      builtWith: 'Built with C',
      liveLink: '',
      gitLink: 'https://github.com/Joshrobertson023/Data-Structures-Algorithms/blob/main/program7.c',
      imageSrc: './images/searching-algorithms.jpg',
      inverse: false,
      category: 'c',
   },
   {
      title: 'tic tac toe',
      displayTitle: 'Tic-Tac-Toe',
      learningOutcomes: 'This project introduced me to various OOP concepts and working with JavaScript objects.',
      builtWith: 'Built with HTML, CSS, and JavaScript',
      liveLink: 'https://joshrobertson023.github.io/tic-tac-toe/',
      gitLink: 'https://github.com/Joshrobertson023/tic-tac-toe',
      imageSrc: './images/tictactoe.jpg',
      inverse: false,
      category: 'webapps',
   },
   {
      title: 'etch a sketch',
      displayTitle: 'Etch-a-Sketch',
      learningOutcomes: 'This introduced me to working with basic logic and syntax in JavaScript. It also introduced me to manipulating a UI with code and working with the DOM.',
      builtWith: 'Built with HTML, CSS, and JavaScript',
      liveLink: 'https://joshrobertson023.github.io/etch-a-sketch/',
      gitLink: 'https://github.com/Joshrobertson023/etch-a-sketch',
      imageSrc: './images/etchasketch.jpg',
      inverse: false,
      category: 'webapps',
   }
]

export {listings};